In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'],test_size = 0.2)

In [10]:
y_train

30    Yes
86    Yes
66     No
84     No
36     No
     ... 
39     No
40     No
93    Yes
7     Yes
75    Yes
Name: has_covid, Length: 80, dtype: object

In [11]:
# First

In [12]:
si = SimpleImputer()

In [13]:
X_train_fever = si.fit_transform(X_train[['fever']])

X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever

array([[101.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [102.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [104

In [14]:
# OrdinalEncoder - > cough

oe = OrdinalEncoder(categories = [['Mild','Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])

X_train_cough.shape

(80, 1)

In [16]:
X_test_cough = oe.fit_transform(X_test[['cough']])

In [17]:
X_test_cough

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [21]:
# OneHotEncoding -> gender,city

ohe = OneHotEncoder(drop = 'first',sparse_output = False)

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])


X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])


In [23]:
X_train_gender_city

array([[1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],


In [24]:
# Extracting Age

X_train_age = X_train.drop(columns = ['gender','fever', 'cough','city']).values

#Also

X_test_age = X_test.drop(columns = ['gender','fever','cough','city'])

X_train_age.shape

(80, 1)

In [29]:
X_train_transform = np.concatenate((X_train_age,X_train_gender_city,X_train_cough,X_train_fever),axis =1)

# also
X_test_transform = np.concatenate((X_test_age,X_test_gender_city,X_test_cough,X_test_fever),axis =1)

In [31]:
X_train_transform

array([[ 15.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        , 101.        ],
       [ 25.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        , 104.        ],
       [ 51.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        , 104.        ],
       [ 69.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   1.        ,  98.        ],
       [ 38.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        , 101.        ],
       [ 47.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        , 101.        ],
       [ 47.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        , 100.        ],
       [ 66.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  99.        ],
       [ 69.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [33]:
# second step

from sklearn.compose import ColumnTransformer

In [35]:
transformer = ColumnTransformer(transformers = [
    ('tnf1',SimpleImputer(), ['fever']),
    ('tnf2',OrdinalEncoder(categories =[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(drop = 'first',sparse_output = False),['gender','city'])
])

In [39]:
transformer.fit_transform(X_train).shape

(80, 6)